# Generated by Django 4.0.4 on 2022-05-12 11:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCommunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='personal_community', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
                ('participants', models.ManyToManyField(related_name='communities', to=settings.AUTH_USER_MODEL, verbose_name='Участники')),
            ],
            options={
                'verbose_name': 'Сообщество пользователя',
                'verbose_name_plural': 'Сообщества пользователей',
            },
        ),
    ]
