# Generated by Django 4.0.4 on 2022-05-12 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=127, verbose_name='Название')),
                ('title_en', models.CharField(max_length=127, verbose_name='Название на английском')),
                ('is_default', models.BooleanField(default=False, verbose_name='Использовать по-умолчанию')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='Позиция в списке')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subtitles', to='creations.creationtype', verbose_name='Заголовок')),
            ],
            options={
                'verbose_name': 'Тип Творения',
                'verbose_name_plural': 'Типы Творений',
                'ordering': ('-position',),
            },
        ),
    ]
