# Generated by Django 4.0.4 on 2022-05-12 11:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('creations', '0002_create_base_creation_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='Creation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('title', models.TextField(verbose_name='Название')),
                ('title_en', models.TextField(null=True, verbose_name='Название на английском')),
                ('status', models.CharField(choices=[('not_confirmed', 'Не подтверждено'), ('in_progress', 'В процессе'), ('protected', 'Защищен')], default='not_confirmed', max_length=63, verbose_name='Статус')),
                ('protected_at', models.DateTimeField(null=True, verbose_name='Дата защиты')),
                ('certificate_number', models.PositiveIntegerField(db_index=True, unique=True, verbose_name='Номер свидетельства')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='creations.creationtype', verbose_name='Тип')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='creations', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Творение (РИД)',
                'verbose_name_plural': 'Творения (РИД)',
            },
        ),
        migrations.CreateModel(
            name='CreationFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('file_type', models.CharField(choices=[('source_file', 'Исходник'), ('signature_file', 'Цифровая подпись')], max_length=63, verbose_name='Тип файла')),
                ('storage_type', models.CharField(choices=[('yandex_disk', 'Яндекс Диск'), ('google_drive', 'Google Диск'), ('inner_storage', 'Внутреннее хранилище'), ('s3_storage', 'AWS S3 хранилище')], max_length=63, verbose_name='Тип хранилища')),
                ('file_name', models.CharField(max_length=255, verbose_name='Имя файла')),
                ('file_size', models.BigIntegerField(null=True, verbose_name='Размер файла')),
                ('check_sum', models.CharField(max_length=255, null=True, verbose_name='Контрольная сумма')),
                ('file_identifier', models.TextField(verbose_name='Идентификатор файла')),
                ('creation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='creations.creation', verbose_name='Творение')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='creations_files', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Файл Творения',
                'verbose_name_plural': 'Файлы Творений',
            },
        ),
    ]
