# Generated by Django 4.0.4 on 2022-05-12 06:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('INFO', 'Выполнено'), ('WARNING', 'Предупреждение'), ('ERROR', 'Ошибка')], max_length=15, verbose_name='Статус')),
                ('event_type', models.CharField(choices=[('unknown', 'Неизвестно'), ('email_does_not_send', 'Письмо не отправлено')], max_length=63, verbose_name='Тип события')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Сообщение')),
                ('traceback', models.TextField(null=True, verbose_name='Трассировка')),
                ('extra', models.JSONField(default=dict, verbose_name='Подробности')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Лог',
                'verbose_name_plural': 'Логи',
                'ordering': ['-created'],
            },
        ),
    ]
